ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  core-js: false
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@rolldown/*"
  - "@vercel/*"
  - "@workflow/*"
  - ai
  - experimental-ai-sdk-code-mode
  - eve
  - nitro
  - rolldown
  - workflow
